# Generated by Django 2.1.2 on 2018-11-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
