# Generated by Django 2.1.2 on 2018-11-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181102_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group_id',
            field=models.IntegerField(default='0000000', editable=False),
        ),
    ]
